# -*- coding: utf-8 -*-
"""Lectores-Escritores.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12X_CI4nS6l9FgyMEDvL-4UoiYCgdv5pe
"""

import time
from sys import stdout

def presentacion ():
  RED, WHITE, CYAN, GREEN, END = '\033[91m', '\33[46m', '\033[36m', '\033[1;32m', '\033[0m'

  print("""
  \033[1;32m
                                  .....                                               ____  ____   ___  ____  _     _____ __   __    _    ____   ____  _____
                          .'cokO000000Okdoc;'...                                    |  _ ||  _ \ | _ || __ )| |   | ____|  | |  |  | |  | ___| |  _ || ____|
                        .;d0NWMMMMMMMMMMMMMWWKko;.                                   | |_) | |_) | | | |  _ || |   |  _| | ||_|| | | _ | |___ | | | | |  _|
                  . .'ckNWWWWMMMMMMMMMMMWWWWWWWXkc.                                 |  __||  _ <| |_| | |_) | |___| |___| |   | || ___ | ___)| | |_| | |___
                ...'c0NWWWWWNWWMMMMMMMWWNNNWWWWWWNO;   ....                         |_|   |_| \_||___||____||_____|_____|_|   |_|_|   |_|____| |____||_____|
              .....'lkXWWWWWNNXKKXWWWWNK00KNNNWWWWWNOc.  ....                     
            ......,l0NXOdc;;clc;cxxdddxl;::;;:ld0NNOo;.  ....                      ____ ___  _   _  ____ _   _ ____  ____  _____ _   _  ____ ___    _    ____
          ..........coc,.      .'.;dxdlc:'.      .;k0o,.......                     | ___| _ || | | || ___| | | |  _ ||  _ || ____| | | || ___|_ _|  | |  | ___|
        ..........',.   ...     .,lc:;'.    ...   .;l'...'...  .                 | |  | | | |  || | |   | | | | |_) | |_) |  _| |  || | |    | |  | _ | |___ |
        ....''....'.   ..''... ...   .''. ..''...   ',. ..'''...                 | |__| |_| | ||  | |___| |_| |  _ <|  _ <| |___| ||  | |___ | | | ___ | ___)|
        ...','....,.   ..:l;',;'       ',..'cc...   .'.  .,''''.                  |____|___||_| |_||____||___||_| |_|_| |_|_____|_| |_||____|___|_|   |_|____|
        ..',,'.'..;'  ...,:c;,'.  ..    ..;lc;'..  ','.  .,''''.                 
        .'',,'.',''',,,;,;:'... .ld;,.  ..';;:;,''','..  .,,'''.                 
        .'',,,..'''.''',,......   ;l;'.  ...........','....','''..                  
        .',,,'...  ....   ...    ';'..     ...     ...'...','''..                
        .....      ..    .'.     .....     .;.     ......  .......                ___  _   _  _____  _____   ____  ____      _     _   _  _____  _____ 
                ...','......          ..     ,:.  'd0kooo;.      .                |_ _|| \ | ||_   _|| ____| / ___||  _ |    | |   | \ | ||_   _|| ____| ____ 
              .:kOkkOOc...                   .. .,cdddkx,         .               | | |  \| |  | |  |  _|  | |  _ | |_) |  | _ |  |  \| |  | |  |  _|  | ___|
                .xX0k0Od,                         ..,,';.                          | | | |\  |  | |  | |___ | |_| ||  _ <  | ___ | | |\  |  | |  | |___ |___ |
          ..    ,l:::,....                    .   ...,,     .                    |___||_| \_|  |_|  |_____| \____||_| \_||_|   |_||_| \_|  |_|  |_____||____|
      .     ..    ...           . ........ .                ..     .                  
      .   .. .                 .  ..... .....                ...        
        .dl..               ..... ..  .....               ..:x,                    1.- Helen Lisbeth Bernal Vera.
          ,:.                 .....   ......               ..;,.                    2.- Joe Fernando Vélez Calero.
                      ..        .........       .                                  3.- Renán Oswaldo Pérez Balladares.
                  ......                        ......                             4.- Jonatán Josué Guillén Salabarria.
                .........                ..   .........                            5.- Manuel Agustin Burgos Ramires.
              .  .''''','..                  .''''''..                 
                ...... ...''......         ..''''.'.....                
                .. ....  ..''..................   .                    
                          ..''...  ....      .                         
                            ............  ..                           
  """)
  print("\033[1;32m                                              _______  ______   ___  ____ ___ ____ ___ ___  _   _  ");
  print("\033[1;32m                                             | ____| \/ |  _ | | _ || ___|_ _| ___|_ _| _ || | | |  ");
  print("\033[1;32m                                             |  _|  |  || |_) | | | |___ || | |    | | | | |  || | ");
  print("\033[1;32m                                             | |___ |  ||  __|| |_| |___) | | |___ | | |_| | ||  | ");
  print("\033[1;32m                                             |_____|_||_|_|    |___||____|___|____|___|___||_| |_|  ");
  print("\033[1;32m                    ____ ___ ____ _____ _____ __  __    _    ____     ___  ____  _____ ____      _  _____ _____     _____  ____"); 
  print("\033[1;32m                   | ___|_ _| ___|_   _| ____|  ||  |  | |  | ___|   | _ ||  _ || ____|  _ |    | ||_   _|_ _| |   | | _ || ___|");
  print("\033[1;32m                   |___ || ||___ | | | |  _| | |||| | | _ | |___ |  | | | | |_) |  _| | |_) |  | _ | | |  | | | | | | | | |___ |");
  print("\033[1;32m                    ___) | | ___) || | | |___| |  | || ___ | ___) | | |_| |  __|| |___|  _ <  | ___ || |  | |  | V || |_| |___) |");
  print("\033[1;32m                   |____|___|____| |_| |_____|_|  |_|_|   |_|____|   |___||_|   |_____|_| |_||_|   |_|_| |___|  |_|  |___||____|\n");
  time.sleep(2)

  for i in range(101):
          time.sleep(0.01)
          stdout.write("\r{0}[{3}*{0}]{2} Iniciando Programa Por Favor Espere... %d%%".format(GREEN, END, CYAN, RED, WHITE) % i)
          stdout.flush()
          time.sleep(0.02)

  print (" ")
  print (" ")

if __name__ == '__main__':
  presentacion ()

# -Lectores y escritores -
import threading as th
import random
import time

personas = 5  
tiempo = 2  # tiempo que demora en leer o escribir en segundos
tiempo_r = random.randint(0,5)  # valor 

semaforo = th.Lock () # semáforo

# global libro  # variable global
# global count  # variable global
libro = 0     # Estado globla del libro: 0-desocupado, 1-ocupado por lector, 2-ocupado por escritor
x = 0         # Contador global la lectores.

def lector (n, i):  # Escritor
  flagl = False  
  global libro
  global x
  print (f'{i} Lector {n}   - Entra a la biblioteca. ')
  while (flagl == False):
    time.sleep (tiempo_r)
    if (libro == 0 or libro == 1):
      x += 1
      if (libro == 0):
        libro = 1
        print (f'{i} Lector {n}   - Está leyendo. ')
      else:
        print (f'{i} Lector {n}   - Se unió a leer. ')
      semaforo.acquire ()
      time.sleep (tiempo)
      print (f'{i} Lector {n}   - Dejó el libro. ')
      semaforo.release ()
      x -= 1
      if (x == 0):
        libro = 0
      flagl = True
    else:
      print (f'{i} Lector {n}   - En espera. ')
      flagl = False
  print (f'{i} Lector {n}   - Dejó la biblioteca. ')

def escritor (n, i):  # Lector
  flage = False
  global libro
  print (f'{i} Escritor {n} - Entra a la biblioteca. ')
  while (flage == False):
    time.sleep (tiempo_r)
    if (libro == 0):
      semaforo.acquire ()
      libro = 2
      print (f'{i} Escritor {n} - Está escribiendo. ')
      time.sleep (tiempo)
      print (f'{i} Escritor {n} - Dejó de Libro. ')
      semaforo.release ()
      libro = 0
      flage = True
    else:
      print (f'{i} Escritor {n} - En espera. ')
      flage = False
  print (f'{i} Escritor {n} - Dejó la biblioteca. ')


if __name__ == '__main__':
  inicio = time.perf_counter () # conteo inicial del tiempo

  hilos = []
  c1 = 1
  c2 = 1
  print ('Libro desocupado.')
  for i in range (personas):  # creación de lectores y escritores de forma aleatoria
    if (random.randint (0, 100) > 50):
      l = th.Thread (target = lector, args = (c1, i+1))
      l.start ()
      hilos.append (l)
      c1 = c1 + 1
    else:
      e = th.Thread (target = escritor, args = (c2, i+1))
      e.start ()
      hilos.append (e)
      c2 = c2 + 1
  for hilo in hilos:
      hilo.join ()

  final = time.perf_counter ()  # conteo final del tiempo
  print (f'\nTiempot total: {round(final-inicio, 2)} segundos.')